### PR TITLE
Update issue template

### PR DESCRIPTION
**Pull request by JN-Hernandez**
Requests user adds issue to the Operations Backlog project.
Auto-assigns the "Kubernetes" label for epic tracking.

### CODE REVIEW

**Comment by BryanQuigley** [comment]
I was just thinking about this recently.    Thoughts on just making it something like 

Delete this line once you've added this issue to the "Operations Backlog" project

You can add it to the Project without creating it first.

**Review by jpolchlo — APPROVED** [review]

**Comment by jpolchlo** [comment]
Do we want to make some additional changes here, or can I merge this to tidy up the repo a bit?

**Comment by jpolchlo** [comment]
bump

**Review by BryanQuigley — APPROVED** [review]
Sorry this was waiting on review

**Pull request merged**
